Added history calculation for all the views
AnthonyH93/HexaCalc pull request #10
Opened 2022-09-28 12:08 UTC by FilippoZazzeroni

I've added the history calculation for all the views. Let me know what you think about it thank you. If this feature can updated in some way you can give me instructions and I'll try to do it.

2022-09-28 22:13 UTC, AnthonyH93 requested changes
Looks very good thanks! Please remove the `.DS_Store` file though since it is causing a merge conflict.

2022-09-28 22:31 UTC, AnthonyH93 commented
In terms of future changes, I would have the following suggestions:
* Technical
  * Add the result of the computation to the table
    * Maybe as part of the same string with an equals sign separator (ex. 6 * 5 = 30)
    * Or as a new column (ex. 6 * 5 | 30)
  * Allow a long press or single click to copy answers from the table 
* Visual
  * Make the background of the calculation history overlay black
  * Make the text of the overlay either white or the colour theme preference
  * Make the navigation text in the corner to open the calculation history overlay the colour theme preference

Feel free to suggest otherwise if you don't think these changes make sense. Again, thanks a lot for the help on this!

Also, do you think it would be good for the history to persist after closing the app or should it only store the current session calculations?

2022-09-30 14:57 UTC, FilippoZazzeroni commented
I will try to implement the things you suggested, that for me all of them make sense. The only thing I don't understand is the copy of the history content if it can be pasted in the calculator later or if that is the purpose. The history so far, I would be keep it run time there s no need to persist it.

2022-10-01 18:11 UTC, AnthonyH93 commented
Thanks for implementing those features. I'll run the app soon and review. Yes, the purpose of copying would be to paste into the calculator later, I suppose we could skip the step of copying and just have it automatically close the overlay and put the number into the calculator when you click on a row, but copying is probably good for now.

2022-10-01 18:44 UTC, FilippoZazzeroni commented
I've already added the copy paste functionality when you click a row. Let me know how is when you try it.

2022-10-01 22:14 UTC, AnthonyH93 requested changes
Please change the copy alert to match the other copy alerts (sorry this one is my fault, I should have a well defined module for copy alerts). Also please delete `.DS_Store` since it is causing a merge conflict.

Other than that it looks awesome, thanks a lot!

2022-10-01 22:14 UTC, AnthonyH93 commented on HexaCalc/View Controllers/CalculationHistoryViewController.swift
> +        let alert = UIAlertController(title: "Result copied to clipboard", message: nil, preferredStyle: .alert)
```suggestion
        let alert = UIAlertController(title: "Copied to Clipboard", message: "\(calculationHistory[indexPath.row].result) has been added to your clipboard.", preferredStyle: .alert)
```

2022-10-01 22:14 UTC, AnthonyH93 commented on HexaCalc/View Controllers/CalculationHistoryViewController.swift
> +        alert.addAction(UIAlertAction(title: "OK", style: .cancel))
```suggestion
```

2022-10-01 22:14 UTC, AnthonyH93 commented on HexaCalc/View Controllers/CalculationHistoryViewController.swift
> +
```suggestion
        DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) {
            alert.dismiss(animated: true, completion: nil)
        }
```

2022-10-05 03:53 UTC, AnthonyH93 approved these changes
Looks great, thanks for making the requested changes!

2022-10-05 04:02 UTC, merged